#ifndef BMI_H
#define BMI_H

#define UNDERWEIGHT 16.0
#define SEVERE_UNDERWEIGHT 16.9
#define UNDERWEIGHT_RANGE 17.0
#define NORMAL_WEIGHT_RANGE_LOWER 18.5
#define NORMAL_WEIGHT_RANGE_UPPER 24.9
#define OVERWEIGHT_RANGE_LOWER 25.0
#define OVERWEIGHT_RANGE_UPPER 29.9
#define OBESITY_I_RANGE_LOWER 30.0
#define OBESITY_I_RANGE_UPPER 34.9
#define OBESITY_II_RANGE_LOWER 35.0
#define OBESITY_II_RANGE_UPPER 39.9
#define OBESITY_III 40.0




#endif
